### ISSUE TITLE
Partial line lists

### ISSUE THREAD

**Issue by jsheen** [epiforecasts/EpiNow#10]
Hello,

I was wondering where the partial line-lists for regions/countries were obtained in order to create the delay functions. The presentation of the EpiNow results (https://cmmid.github.io/topics/covid19/current-patterns-transmission/global-time-varying-transmission.html) refers to the WHO situation reports for the total case counts per day, but I was unable to find where partial line-lists were obtained. 

Thank you for the results so far.

**Comment by seabbs** [comment]
Thanks for reaching out. 

Linelist link (limited by user count so may take a while to load): https://docs.google.com/spreadsheets/d/1itaohdPiAeniCXNlntNztZ_oRvjh0HsGuJXUJWET008/pub

Extracted with: https://github.com/epiforecasts/NCoVUtils/blob/master/R/get_international_linelist.R
