### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by magecu** [epiforecasts/EpiNow#44]
On my machine the docker build fails with:
![image](https://user-images.githubusercontent.com/35303103/78645566-03208580-78b8-11ea-9304-758c2e778d8b.png)

**Comment by seabbs** [comment]
Thanks for the heads up. Any suggest fixes would be appreciated. Alternatively, we will look at fixing shortly

**Comment by magecu** [comment]
I have tired various versions of rocker/geospatial, but it didn't help.

Then I removed rnaturalearthhires from sugested in DESCRIPTION, but got to a new blocker.
![image](https://user-images.githubusercontent.com/35303103/78664780-fc543b80-78d4-11ea-8a00-e4936fbe705a.png)

**Comment by seabbs** [comment]
Hi @magecu, 

I tried this yesterday with the current master and everything worked. It may be the case that we have fixed this inadvertently! 

Let me know if still broken for you. Sorry for the frustration.

**Comment by magecu** [comment]
Still wasn't able to build it on the virtual (virtualbox) machine with ubuntu 18.04.4.
But was able to build it on my ubuntu 18.04 server.

**Comment by seabbs** [comment]
Hmm that is very odd. Do you have the log output - would be good to get this sorted out.

**Comment by magecu** [comment]
Seems like there were an issue with docker.
Even though I have restarted the system several times, It didn't start to work  until i restarted the docker daemon with systemctl.
And I found it out only because I tried to access the logs to append them here. 
Now it went trough. 
Thank you for all the help!
In the end it seems there was an issue with docker.

**Comment by seabbs** [comment]
Great glad we got there!
