### ISSUE TITLE
Stan issue: mk_cppmodule

### ISSUE THREAD

**Issue by pucciami** [epiforecasts/EpiNow#45]
Epidemiologist without modeller friends nearby getting desperate here... :)

**line 53 dist_fit.R**
fit <- rstan::sampling(...

mk_cppmodule = function(x) get(paste0("model_", model_name)
Error in get(paste0("model_", model_name)) : 
  object 'model_exp_fit' not found

I have run the stanmodels function, the stanmodel objects are up. Still this call in the mk_cppmodule is pointing to a missin object...i don't get it and, as such, cant figure out the fix.

Thx for you great work. It is of immense use for all of us.

**Comment by seabbs** [comment]
Hi @pucciami, 

Have you built/installed the EpiNow package? This framework assumes that you have.

**Comment by pucciami** [comment]
Hi @seabbs (from the long version of your handle I now I see I have also just sent you an official mail form our institute :))

Yes the package is installed.

**Comment by seabbs** [comment]
So you shouldn't need to run the stanmodels function (and shouldn't). You should just be able to use `EpiNow::dist_fit` as a built function?

**Comment by pucciami** [comment]
True... and  I am using it. It gives the error code so I was delving deeper to debug.

**Comment by seabbs** [comment]
Did you build the package locally? If so did you compile the stan code first?

**Comment by pucciami** [comment]
I did the package install as per readme:
remotes::install_github("epiforecasts/EpiNow", dependencies = TRUE)

(docker - issue 44- was not an option sadly)

**Comment by seabbs** [comment]
Hi @pucciami,

I haven't been able to replicate this, unfortunately. We are all using docker so perhaps that is the issue?

Could you give me some system details as that might be the cause of the problem.

**Comment by pucciami** [comment]
Hey @seabbs!
Managed to get Docker on (working on Linux). Functions running great.
And kudos for the Slovenia add! Still working on it myself, but is of great use for us.

**Comment by seabbs** [comment]
Fantastic news and no problem. 

If you ever trace down the root issue you were having would be good to know so we can squash but I can imagine not a priority.
