### ISSUE TITLE
workflow from case to EpiSoon::example_obs_rts

### ISSUE THREAD

**Issue by philipus** [epiforecasts/EpiNow#60]
Hi

do you have an easy workflow for EpiNow to get from cases to a times series like in the example EpiSoon::example_obs_rts example??

I think it is hided in the covid repo but maybe it would be cool to have some intro line here too.

Best

Filip

PS: Great work!

**Comment by seabbs** [comment]
Thanks for opening this and sorry for the delay. There are now simple examples in `rt_pipeline` and `regional_rt_pipeline` to help with getting started.
