### ISSUE TITLE
Troubleshooting in usage of regional_rt_pipeline

### ISSUE THREAD

**Issue by praveentiru** [epiforecasts/EpiNow#82]
@seabbs I am working on building a regional pipeline for India. My work [here](https://github.com/praveentiru/rtIndia-EpiNow).

I am not a statistician but a programmer. I have been able to build the pipeline and run analysis today. I am bit concerned with nowcast plots that were generated for regions in India. Attached is an example for a region. As you can see, doubling day values become halving days and vary widely. 
![rate_spread_plot](https://user-images.githubusercontent.com/12044936/80915006-eff4be80-8d6c-11ea-8284-6cbc6fa0c6ee.png)

One major issue I see is that I do not have a source that will help with linelist which I believe is being used to estimate delay between onset to confirmation. There is volunteer run India patient DB but, it does not hold any values for estimated onset date.

Any advice that you can provide to clean-up my code will help me integrate output to https://www.covid19india.org/ portal.

**Comment by seabbs** [comment]
Hi @praveentiru, 

Sorry about missing this previously. 

We are now depreciating EpiNow and I think most of these issues should be resolved in [EpiNow2](https://github.com/epiforecasts/EpiNow2) please let me know if this is not the case.
