### ISSUE TITLE
Broken link to www.epiforecasts.io

### ISSUE THREAD

**Issue by edbaskerville** [epiforecasts/EpiNow#92]
The EpiNow GitHub page points to [https://www.epiforecasts.io/EpiNow](https://www.epiforecasts.io/EpiNow), but only [https://epiforecasts.io/EpiNow](https://epiforecasts.io/EpiNow) actually works.

**Comment by jhellewell14** [comment]
Fixed! Thanks for pointing this out.

Cheers,
Joel
