### ISSUE TITLE
Usage of delay_def instead of incubation_def in simulation.

### ISSUE THREAD

**Issue by fvalka** [epiforecasts/EpiNow#98]
https://github.com/epiforecasts/EpiNow/blob/38c88ce93ddb7e62c5429766572e295f6dd247c6/R/simulate.R#L67

I think that should be `incubation_def` instead of `delay_def`.

All the best

**Comment by seabbs** [comment]
Good spot thanks. Saved me some time here! Fixed now.

**Comment by fvalka** [comment]
You're welcome and thanks for fixing it! 👍
